### ISSUE TITLE
Any way to bypass the "certificate mismatch" issue?

### ISSUE THREAD

**Issue by KKPMW** [Oxygem/Kanmail#89]
In one of my mail boxes I have this "certificate mismatch" error when trying to add it to Kanmail:

> [Errno 1] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'imap.servername.lt'. (_ssl.c:1076)

I think the issue stems from the fact that my folder is "imap.servername.lt", while the certificate is for "servername.lt", but I am not sure since my knowledge about how email servers work is quite limited. 

But what I do know is that I can bypass this issue in i.e. mutt by adding the following setting to the configuration: `unset ssl_verify_host`.

Is there some way to bypass this issue in Kanmail?

**Comment by Fizzadar** [comment]
@KKPMW this should be possible to achieve; I think I'll need to add a specific account setting for it to disable hostname verification (https://docs.python.org/3/library/ssl.html#ssl.SSLContext.check_hostname).

**Comment by KKPMW** [comment]
@Fizzadar that would be grand, as this issue affects my main mailbox, and so I sadly had to pause using the app for now.

But I really like the app and can't wait to use it again daily.

Will be monitoring this issue and eagerly waiting for updates.
Thanks a lot!

**Comment by Fizzadar** [comment]
@KKPMW I have just released `v1.2004301944` which includes an option to disable hostname checking! It's found within the IMAP/SMTP account settings (flagged advanced) :)

**Comment by KKPMW** [comment]
@Fizzadar Thank you for being so fast with the changes.

Unfortunately I am still getting the same error, no matter if the box is checked or unchecked.. Here is the exact error message:

> [Errno 1][SSL:CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate not valid for 'imap.servername.lt'. (_ssl.c:1076)

**Comment by KKPMW** [comment]
And I also tried to turn off SSL entirely, but then getting the following:

> [SSL: UNKNOWN PROTOCOL] unknown protocol (_ssl.c:1076)

Is there a way I could help further? Maybe some logs I can send or something of this kind?

**Comment by KKPMW** [comment]
Just as a sanity check I tried to connect to the same mailbox with the same settings using Apple Mail, and it did so. It just threw a warning about not being able to verify host certificate, I pressed "continue anyway" and it worked.

**Comment by Fizzadar** [comment]
I just tested this w/Fastmail (made up host in `/etc/hosts`) and it worked as expected (same error w/verify, no error without), which further complicates this :/ I've fired an email over to you to debug further.

**Comment by KKPMW** [comment]
Thanks a lot for all your help @Fizzadar 

I emailed you the login details to one of the boxes. If it will help you - feel free to try them out with mutt or Apple mail (I tried those 2 and they work for me), or any other mail client.

Hope this will be helpful, if you need something in addition, just let me know.

**Comment by Fizzadar** [comment]
@KKPMW the latest release should now respect the flag when adding a new account, which should clear this up for you!

**Comment by KKPMW** [comment]
Thanks a lot @Fizzadar it is working now!

One error I get after connecting is this: 

> Index Error: tuple index out of range

But everything seems to be working so not sure how serious it is. It is displayed at the top left corner. In any case, unrelated to this issue, so I think this one can be closed now.

Will be using Kanmail as my main email client now.

**Comment by KKPMW** [comment]
@Fizzadar So looks like this error is related to the "initial number of batches to fetch". I changed it to 1 (not sure if good idea), and it disappeared.

**Comment by Fizzadar** [comment]
@KKPMW excellent news; glad it's working for you :) Closing this now, I've added #104 to track the out of range error.
